project:
  type: website
  output-dir: docs

website:
  title: "learnr.fun - เว็บง่ายๆ ใช้ R ทำงานและทำเงิน"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: hello.qmd
        text: Helo World

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

